pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Code QL
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: rebase