name: CD (Preview)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'

permissions: read-all

jobs:
  dev_deploy:
    name: Build and Deploy for Preview
    if: ${{ github.repository == 'sws2apps/sws2apps-web' && github.ref == 'refs/heads/main' }}
    environment:
      name: Preview
      url: https://preview-admin.sws2apps.com
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Build the website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
          VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
          VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
          VITE_BACKEND_API: ${{ secrets.VITE_BACKEND_API }}

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6
        with:
          files: 'dist'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: sws2apps/firebase-deployment@6fbedc5c04fd9b29e73ed3ea173be81e8a097153
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          project: 'dev-sws2apps'
